EC/ROCM: Fix uninitialized variable error by clang
Clang compiler reports this error at make:
../../../../../src/components/ec/rocm/ec_rocm.c:351:13: error:
        variable 'status' is used uninitialized whenever 'if' condition is true

This patch fixes it.